"""auto vote

Revision ID: 04eb21c33d70
Revises: f5c9b8fd5f2f
Create Date: 2022-06-24 18:07:20.647298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04eb21c33d70'
down_revision = 'f5c9b8fd5f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
